default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: <%= ENV['DB_NAME']%>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_URL'] %>
  port: <%= ENV['DB_PORT'] || 5432 %>

test:
  <<: *default
  database: <%= ENV['DB_TEST_NAME']%>
  username: <%= ENV['DB_TEST_USERNAME'] %>
  password: <%= ENV['DB_TEST_PASSWORD'] %>
  host: <%= ENV['DB_TEST_URL'] %>
  port: <%= ENV['DB_PORT'] || 5432 %>


production:
  <<: *default
  database: <%= ENV['DB_NAME'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_URL'] %>
  port: <%= ENV['DB_PORT'] || 5432 %>